name: Build dxapi
on: [push]
jobs:
#   Build-Dxapi-Linux:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v2
#       - run: make -C .
#         env: 
#           CC: clang
  Build-Dxapi-Windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - run: pwd
    - run: ls
    - run: C:/Program` Files` `(x86`)/Microsoft` Visual` Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe ./prj/dxapi.vcxproj /p:configuration=release /p:platform=x64 /t:rebuild

