name: Build dxapi

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    branches:  [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        conf: ['']
        include:
          - os: macos-latest
            env_os: MACOS
          - conf: debug
            os: windows-latest
          - conf: release
            os: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        run: make -C .
        env:
          CC: clang
          OS: ${{ matrix.env_os }}
      - name: Use MSBuild
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build Solution
        if: ${{ matrix.os == 'windows-latest' }}
        run: msbuild dxapi.sln /p:configuration=${{ matrix.conf }} /p:platform=x64 /t:rebuild
      - name: Archive artifacts linux-mac
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@v2
        with:
          name: dxapi-${{ matrix.os }}
          path: |
            include/native/**/*.h
            bin/libdxapi-x64.a
      - name: Archive artifacts win
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v2
        with:
          name: dxapi-${{ matrix.os }}-${{ matrix.conf }}
          path: |
            include/native/**/*.h
            bin/dxapi-x64.lib
            bin/dxapi-x64d.lib
            bin/dxapi-x64d.pdb
