name: Build dxapi

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    branches:  [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: macos-latest
            env_os: MACOS
          - os: windows-latest
            conf: debug
          - os: windows-latest
            conf: release
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        run: make -C .
        env:
          CC: clang
          OS: ${{ matrix.env_os }}
      - name: Use MSBuild
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build Solution
        if: ${{ matrix.os == 'windows-latest' }}
        run: msbuild dxapi.sln /p:configuration=${{ matrix.conf }} /p:platform=x64 /t:rebuild
      - name: Archive artifacts linux-mac
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@v2
        with:
          name: dxapi-${{ matrix.os }}
          path: |
            include/native/**/*.h
            bin/libdxapi-x64.a
      - name: Archive artifacts win
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v2
        with:
          name: dxapi-${{ matrix.os }}
          path: |
            include/native/**/*.h
            bin/dxapi-x64.lib
            bin/dxapi-x64d.lib
            bin/dxapi-x64d.pdb
        
# jobs:
#   build:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, macos-latest]
#         include:
#           - os: macos-latest
#             env_os: MACOS
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v2
#       - name: Build Dxapi
#         run: make -C .
#         env: 
#           CC: clang
#           OS: ${{ matrix.env_os }}
#       - name: Archive artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: dxapi-${{ matrix.os }}
#           path: |
#             include/native/**/*.h
#             bin/libdxapi-x64.a
            
#   build-windows:
#     runs-on: windows-latest
#     strategy:
#       matrix:
#         conf: [debug, release]
#     steps:
#     - name: Check out repository code
#       uses: actions/checkout@v2
#     - name: Use MSBuild
#       uses: microsoft/setup-msbuild@v1.0.2
#     - name: Build Solution
#       run: msbuild dxapi.sln /p:configuration=${{ matrix.conf }} /p:platform=x64 /t:rebuild
#     - name: Archive artifacts
#       uses: actions/upload-artifact@v2
#       with:
#         name: dxapi-windows-${{ matrix.conf }}
#         path: |
#           include/native/**/*.h
#           bin/dxapi-x64.lib
#           bin/dxapi-x64d.lib
#           bin/dxapi-x64d.pdb
    
