name: Build dxapi
on: [push]
jobs:
#   Build-Dxapi-Linux:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v2
#       - run: make -C .
#         env: 
#           CC: clang
  Build-Dxapi-Windows:
    runs-on: windows-latest
    steps:
      - run: MSBuild.exe dxapi.sln
