name: Build dxapi
on: [push]
jobs:
  Build-Dxapi-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build Dxapi
        run: make -C .
        env: 
          CC: clang
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dxapi-linux
          path: |
            iclude/native/**/*
            bin/libdxapi-x64.a
  Build-Dxapi-MacOS:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build Dxapi
        run: make -C .
        env:
          CC: clang
          OS: MACOS
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dxapi-macos
          path: |
            iclude/native/**/*
            bin/libdxapi-x64.a
  Build-Dxapi-Windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Build Solution
      run: C:/Program` Files` `(x86`)/Microsoft` Visual` Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe dxapi.sln /p:configuration=release /p:platform=x64 /t:rebuild
    - name: Build Debug Solution
      run: C:/Program` Files` `(x86`)/Microsoft` Visual` Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe dxapi.sln /p:configuration=debug /p:platform=x64 /t:rebuild
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dxapi-windows
        path: |
          iclude/native/**/*
          bin/dxapi-x64.lib
          bin/dxapi-x64d.lib
          bin/dxapi-x64d.pdb
    
